### ISSUE TITLE
Projekt Organisation aufsetzen

### ISSUE THREAD

**Issue by gabrieltorresgamez** [Sensor-Based-Activity-Recognition/.github#1]
Setup GitHub Org + Zotero

**Comment by gabrieltorresgamez** [comment]
Wieso wird bei einem abgeschlossenen Pull Request auf Status Zurückgestellt gestellt.

**Comment by florinbarbisch** [comment]
https://github.com/orgs/Sensor-Based-Activity-Recognition/projects/1/workflows/6488661 wegen dem
